 *Artificial Intelligence for Vision & NLP* &nbsp; | &nbsp;  *ATU Donegal - Postgrad Diploma in Big Data Analytics & Artificial Intelligence*

# Student Submisison 
Name           : Selvi Ganesh Kumar                <br>
Student Number : L00196360          <br>
Due Date       : 12th May 2026                <br>
Assignment     :             <br>
Module         : AI for Vision and NLP    <br>
Course         : Postgraduate Diploma in Big Data Analytics and AI

## NLP and Vision Pipeline : High Level
An image of your working pipeline at high level can be inserted here

# Initialisation
Perform pip installs(or use a requirements.txt) <br>
perform imports

## Install packages

In [5]:
# pip installs

requirements = """
opencv-python
pytesseract
numpy
matplotlib
pandas
pymupdf
easyocr
tqdm
pillow
"""

with open("requirements.txt", "w") as f:
    f.write(requirements.strip())

In [6]:
# pip install -r requirements.txt

## Imports

In [8]:
# imports

import os
import re
import zipfile

import numpy as np
import pandas as pd

import cv2
import matplotlib.pyplot as plt

import pytesseract
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

import pymupdf 
import fitz

from tqdm import tqdm

# Support Functions

In [10]:
# code here

def preprocess_image(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)
    thresh = cv2.threshold(blur, 150, 255, cv2.THRESH_BINARY)[1]
    return thresh

# NLP

## Sub Heading 1

## code

In [13]:
# The dataset has different filtypes: .jpg (images), .bmp (images) and .pdf (documents)
# ZIP → extract → detect file type → extract text → NLP → output

### Image loading

In [15]:
# STEP 1: Extract ZIP
import zipfile
import os

path = r"C:\Education\M.Sc Documents\Computer Vision & NLP\CA2\documents_ca2.zip"

with zipfile.ZipFile(path, "r") as zip_ref:
    zip_ref.extractall("docs")

In [16]:
# To view the extracted files from the zip.

folder = "docs"

for root, dirs, files in os.walk(folder):
    print("Folder:", root)
    print("Files:", files)

Folder: docs
Files: []
Folder: docs\.ipynb_checkpoints
Files: []
Folder: docs\documents_ca2
Files: ['aloevera_back.jpg', 'cartoon_drawing.pdf', 'drawing_using_words.bmp', 'know_receipe.pdf', 'research_paper.pdf', 'scikit_learn.pdf', 'trinity_brochure.pdf']

In [17]:
# step 2: Separate file types and storing them in their own variety, for further processing

jpg_files = []
bmp_files = []
pdf_files = []

for root, dirs, files in os.walk(folder):
    for file in files:
        path = os.path.join(root, file)

        if file.lower().endswith((".jpg", ".jpeg", ".png")):
            jpg_files.append(path)

        elif file.lower().endswith(".bmp"):
            bmp_files.append(path)

        elif file.lower().endswith(".pdf"):
            pdf_files.append(path)

print("JPG:", len(jpg_files))
print("BMP:", len(bmp_files))
print("PDF:", len(pdf_files))

JPG: 1
BMP: 1
PDF: 5

### OCR using Tesseract on images

In [19]:
# step 3: storing the images in the images files to process images (ocr)

image_files = jpg_files + bmp_files

results = []

for file in image_files:
    img = cv2.imread(file)

    processed = preprocess_image(img)
    custom_config = r'--oem 1 --psm 6'  

    text = pytesseract.image_to_string(processed, config = custom_config)

    results.append({
        "file": file,
        "type": "image",
        "text": text
    })

In this project, a hybrid approach was adopted for processing PDF documents to ensure robust and accurate text extraction across different document types. PDFs can broadly be categorised into two types: text-based PDFs, which contain embedded digital text, and scanned PDFs, which are essentially images of documents and do not contain extractable text. To handle both cases effectively, the system first attempts to extract text directly using PyMuPDF, which is efficient and preserves formatting when digital text is available. If no text is detected on a page (i.e., the extracted content is empty or minimal), the system assumes the page is image-based and applies Optical Character Recognition (OCR) using Tesseract. In this case, the PDF page is converted into an image and processed to extract text. This hybrid strategy improves both performance and accuracy by avoiding unnecessary OCR on text-based documents while still enabling text extraction from scanned or image-based PDFs. It also demonstrates a practical integration of document analysis techniques, aligning with real-world multi-modal document understanding systems.

In [21]:
# handling the pdf files separately, either by converting into image for scanned pdf, or by extracting the text directly, 
# incase of read text based pdf, them the text is extracted:


for file in pdf_files:
    doc = fitz.open(file)

    text = ""  # one full document text

    for page in doc:
        extracted = page.get_text()

        if extracted.strip():
            text += extracted + "\n"

        else:
            pix = page.get_pixmap(dpi=200)

            img = np.frombuffer(pix.samples, dtype=np.uint8)
            img = img.reshape(pix.height, pix.width, pix.n)

            custom_config = r'--oem 1 --psm 6'
            text += pytesseract.image_to_string(img, config=custom_config) + "\n"

    results.append({
        "file": file,
        "type": "pdf",
        "text": text
    })

### Basic text extraction from visual data

In [23]:
results

[{'file': 'docs\\documents_ca2\\aloevera_back.jpg',
  'type': 'image',
  'text': 'See WET JUICE, weit; criabies US to capture trie\nnatural properties of the Aloe vera plant. This\ncooling gel nourishes, soothes and can help |\nrestore dry and problem skin. It can also be\napplied to stretch marks, scars and dry or sun\nexposed skin. |\nNatural actives: Organic Aloe Vera.\nBeneficial properties: Soothing, Cooling,\nRestoring, Nourishing\nDirection ‘ | in, Repeat as often a:\nrequired Over the bod,\n(supery :\nIndicazi § 5 senie la necessit.\n(supervis, ad\nAvvertenz a, =. /contatts con gh accel\n“so ch COM au OLEH Hate, MIO GuUTe cul abbcidante acqua \'\nt POCare SU Cute lesa. IN Caso di rritazione cutanea sospendere «\nconte Tuttliz20 di questo prodotto se. si @ allergic’ a qu.’\non oonente, Tenere lontano dalla portata dei bambini. Conserv"\n4090 fresco e€ asciutto, al riparo dalla luce.\n}\n| Aloe Vera Inner Gel —\n\\ Not fo, intemal\n\\ Ne Water, Dg not Avoid contact with eyes. Ini case of accidental (Ci\nee ths Droduct et 10 open wounds. If sansitivity occurs ce!"\n\\> “FD out of you are allergic or sensitive to any of th":\n. ach of children, Store in a cool tof din\na 4: (- . a cool, dry place ou\n\\ "Cents. cee\ntog ‘ Aloe p. d\n. . " Kay aes (Aloe Vera) Leaf Ol i 5 -\n: a Panthiengy . Alkyl Acrylate a s- ~\n; ; “hg NOxyet Odum Phytate, Sodium On -\nA tf anol Potassitum Sorbate \' _\nve.\n; ‘ i)\n| | LL ’\n¥\nre, .\n'},
 {'file': 'docs\\documents_ca2\\drawing_using_words.bmp',
  'type': 'image',
  'text': 'Yt She\nSe A ge ee 9 tok gi aa\nvie? i Been whe 6 oe dass bam\nBet ales f fe ¢ wr)\nSORE IN N AS etrhy yea\nBet gentene ye _ NS\nVISA ee ss\nSRE ec OR Ss Coa ee\nRiley waft 25 Og foo Fou = 0\nhe ar FS aid se\n\n$e. aetey ry NO o gg F -_ FP | ai\n'},
 {'file': 'docs\\documents_ca2\\cartoon_drawing.pdf',
  'type': 'pdf',
  'text': '4\nLesson\nFamous Artists Cartoon Course\nThe comic head\nDrawing the balloon head\nBefore beginning to draw cartoon heads, you must learn to draw\nthe balloon shape freely and quickly. Never use a compass. To\nform your balloon, swing the pencil around several times on the\npaper. The freely drawn balloon will be only a guide for the\ngeneral shape of the head, so make it light - you can strengthen\nthe outline later. Practice drawing balloons about the size shown\nhere, because most of your work as a cartoonist will call for\nheads this size or smaller.\nAfter you have gotten the hang of drawing the balloons and\ncan dash them off easily, you are ready to swing the two guide\nlines in. Sketch these lines as though they go completely around\nthe balloon. This will give the head a solid, three-dimensional\nquality and keep you from drawing flat, pancake-type faces.\nThen start drawing in the eyes, nose, mouth and ears, following\nthe principles demonstrated here.\nFront\nview\nEye line\nSide\nview\nCenter line\nSwing balloon in freely.\nDon\'t use a compass\nAdd guide lines\nDon\'t draw it like this\nwith a single hard line\nEars on\neye line\nEach eye sam\ndistance from\ncenter line\n1 Draw the balloon shape\n2\nAdd the guide lines\n3\nLocate the features\n3/4 Front view\nFront\nto side\nNose and mouth\nlind\nEar behind\ncenter of\nEye close to edge\nof balloon\nEye line\nhead\nDotted line in center\nof balloon helps lo-\ncate ear\nNose extends out\nfrom balloon\nThe center line indicates the direction the head faces. The more\nthe head turns to the side, the more the center line curves.\n1\nCenter line curves as head\nturns from dead center\n2\nEyes located in proper re-\nlation to center line\n3\nNose on center line-side\nof nose shows\nAs the head turns, the\nnose projects outward\nfrom the balloon\nEar at rear of head\nBy varying the amount of curve to the center line, the head can be made to turn to any\ndesired position. Note how the ear moves toward the center as the head turns to the side\nAdd details (eyebrows, hair,\nетls (eyebrows, nair,\nwrinkles, etc.) - firm up outline\nIf the head faces in the opposite di-\nrection, the center line will be cury-\ning in that direction\nΟ\nO\n\nLesson\nFamous Artists Cartoon Course\nThe comic head\nThe eyes and mouth\nmake the expression\nFacial expression\nIf a cartoon character is to be animated and interesting\nto the reader, it must express exactly the right emotion.\nLater in the Course we will show you how the whole fig-\nure can be used to express emotions, but, for now, we are\nconcerned with the head and face. Joy, sorrow, anger,\nand other moods are shown chiefly in the face and you\nshould learn all you can about how to draw them.\nA good way to begin is to study the faces of the people\naround you, and the difterent moods they express. Also,\nset up a mirror and study your own features as you regis-\nter various emotions. See what happens to eyes, eyebrows,\nmouth corners, etc., and practice drawing what you see.\nA good cartoonist doesn\'t just think of his character\'s\nexpressions and emotions - he feels them. This is what\ngives his characters conviction. Watch even the most ex-\nperienced cartoonist at work and you will note that when\nhe draws an unusual expression on the face of a char-\nacter, his own face unconsciously assumes that expression.\nHead gestures\nGive the facial expression more punch and drama by\ndrawing the head in an attitude or gesture that matches\nthe emotion expressed by the features. Again, stand in\nfront of a mirror and try out some of the basic expres-\nsions. Note how naturally the head takes a position that\ncorresponds to the expression. When you laugh, the head\ngoes back. When you look dejected, it goes down. For\nnearly every facial expression there is a head gesture.\nPractice these gestures and apply them in your work.\nDejected-Head droops\nPleased-Mouth curves\nupward\nAmused-Mouth partly\nopen and corners raised\nHilarious-Mouth wide,\neyes half closed\nSad-Mouth curves\ndownward\nSurprised-Mouth an\nuth an\n"O," eyebrows raised\nFrightened-Mouth\nwider, eyebrows high\nDispleased-Mouth\ncorners turned down\nGrim-Mouth a straight\nline, eyes squinted\nAngry-Eyes \nAngry-Eyes glar\nglaring\nteeth bared\nBelligerent-Head\nthrust forward, jaw\njutting out\nAlarmed-Head recoils\nbackward\nHilarious-Head thrown back\nSurprised or amazed\n-Head forward,\nmouth open\n9\n\n10\nAll cartoon characters are based on real people\nAll cartoon heads, regardless of the style of drawing, are based\non real people. To turn a real head into a cartoon head you\nmust do two things: (1) Eliminate detail and (2) exaggerate\noutstanding characteristics. This enables you to express the feel-\nings and personality of the character clearly and sharply.\nTo show you what we mean, we had four cartoonists draw\ntheir interpretations of three models. Their drawings, ranging\nfrom the realistic to the highly stylized, appear below. Note\nthat each man has created a unique and individual cartoon\nwhile expressing the type and personality of the model.\n00000\nThe realistic or adventure-typе\nheads in this column are closest\nto the live models. Still, much\ndetail has been eliminated\nBy simplifying the features-par-\nticularly the eyes and hair- the\nheads can be cartooned\nsemi-realistic manner\nWith more exaggeration of the\noutstanding features and further\nsimplification of outline, the char\nacters become pure cartoons\nEven with extreme exaggeration\nand stylizing, the heads in this\ncolumn are still essentially the\nsame as those in the first column\nPractice drawing\ndifferent types of heads\nDon\'t be satisfied to perfect yourself in\ndrawing just a few types of heads and\nthen go on repeating them forever. Con-\ntinue to practice both from observation\nand memory. There are over two billion\nand memory. There are\npotential characters on this earth, so you\nshould never be at a loss for a fresh\nmodel. Remember that "you learn to\ndraw by drawing"\nΟ\n\n'},
 {'file': 'docs\\documents_ca2\\know_receipe.pdf',
  'type': 'pdf',
  'text': 'Soups Recipe Book \n1 \n\nContents \nRecipes \nQuick & Easy Soups – 20 mins or less \n8 \nCreamy Pea Soup \n10 \nCaulifower Cheese Soup \n12 \nSweet Potato, Coconut & Lime Soup \n14 \nTomato & Basil Soup \n16 \nMexican Veggie Soup with Tortilla Chips \n18 \nCarrot & Coriander Soup \nPerfect Weekday Soups – 30 mins or less \n19 \nMinestrone Soup \n20 Red Thai Curry Lentil & Sweet Potato Soup \nIndulgent Soups – over 30 mins \n22 Squash & Pumpkin Soup \n24 Slow-Cooker Leek and Potato Soup \n4 \nSoups Guide \n6 \nWhat Is The Future 50 Foods Report? \n“To feel safe & warm on a cold wet \nnight all you really need is soup.” \nLaurie Colwin \n \n \n \n \n \n \n \n \n \n \n \n \nYour Guide To Soups \n2 \n3 \n\nJackfruit \nWhy not try going \nmeat free one day \na week with these \neasy swaps – try \nMeat Free Mondays \nLegumes \nPulled pork \nSteak \nPortobello \nmushrooms \nSausages \nCarrots \nChicken \nTofu \nMince \nYour Guide To Soups\n \n \n \n  \n  \n  \n  \nSoups Guide \nWhatever the season, there are few dishes more comforting to \nprepare or eat than a warming bowl of soup. Whilst also being  \na great way to use up leftover ingredients from your fridge,  \nnot to mention helping to keep your shopping costs down.  \nSome of the recipes in this book contain \nYou can also make easy swaps with your \ningredients from our Future 50 Food \nfavourite recipes, even just for one day \nReports, read on to learn about the \na week. Look out for our ideas over the \nreport and the ways in which you can \npage on how you can ‘cheat on meat’. \nmake easy swaps in everyday cooking. \n4\n5 \n\nWhite potatoes \nFOR \nSweet potatoes \nKidney beans \nFOR \nAdzuki beans \nSWAP \nLettuce \nFOR \nWatercress \nADD+ \nSesame seeds \nADD TO GARNISH SOUPS \nWalnuts \nCHOP & SCATTER \nAS A GARNISH TOO \nSpinach \nADD TO GREEN SOUPS \nAND BLEND \nconsuming natural resources  \nquicker than they can be regenerated. \nThe Future 50 Foods have been selected \nbased on their nutritional value and \nrelative environmental impact amongst \nother factors, and whilst there are 50 foods \nglobally, the most common foods found \nin the UK include Spinach, Lentils, Sweet \nPotato and Broad Beans. \nCheck out the F50 Foods report  \nto see what foods you can swap: \nWhat Is  \nThe Future 50 \nFoods Report? \nREAD MORE HERE \nTogether with the WWF (the World \nWide Fund for Nature), we’ve launched \nThe Future 50 Foods report which is a \ncollection of diverse plant-based foods \nfrom around the world that can boost \nthe nutritional value of our meals whilst \nreducing the environmental impact of \nour food supply. \nWhy have we done this? Well, whilst the \nglobal population is growing, so is the \ndemand for agricultural raw materials. \nAbout 75% of what the world currently \nconsumes relies on just 12 crops and 5 \nanimal species, when there are actually \nover 5,000 species that we could be \neating. As a result, we are  \nLook out for \nFuture 50  \nFood pop ups \nwhich tell you \nmore about that \ningredient \nYour Guide To Soups\n  \n \n \n \n \n \n \n  \n \n \n \n \n \n \n \n \n  \n \n \n \n \n \n  \n \n \n6\n7 \n\nCreamy Pea Soup \nPerfect mid-week lunch when working from home as it’s ready \nin just 15 minutes! \nIngredients \n1 Knorr Vegetable \nStock Pot \n600g frozen peas \n1 onion, chopped \n2 cloves garlic, chopped \n800ml water \n200ml double cream \n1 tbsp olive oil \nFreshly ground pepper \nTo Garnish \nDill leaf \nCook \n1. Heat the oil in a saucepan over a \nmedium heat. Add the onion and \ngarlic then fry for 3–4 minutes, until \nsoftened. \n2. Add the boiling water, frozen peas \nand Knorr Vegetable Stock Pot and \nbring to the boil. Reduce the heat  \nand simmer for 10 minutes. \n3. Cool slightly, then add half the cream \nand use a hand blender to liquidise \nthe soup. \n4. Season to taste with pepper and  \nuse the rest of the cream and dill for \nthe garnish. \nCooking time \n10 \nmins \n5 \nmins \n4 \npeople \nEASY \nDifculty \nPrep time \nServes \nKnorr ingredient \nKey \nThis recipe  \ncan also be \nused with a \nSTOCK\nCUBE \nYour Guide To Soups\n  \n \n \n \n \n \n \n \n \n \n8\n9 \n\nThis rich and creamy caulifower soup with an irresistible tang  \nis just the ticket on a chilly day - and it’s inexpensive too. \nCooking time \n20 \nmins \n20 \nmins \n4 \npeople \nEASY \nDifculty \nPrep time \nServes \nKnorr ingredient \nKey \nIngredients \n2 Knorr Vegetable Stock Cubes  \ndissolved in 1L of water \n2 large caulifower, cut into forets \n1 large leek, sliced \n4 garlic cloves, bashed \n2 tbsp olive oil \n200g grated Gruyère \n100g grated Parmesan \n50ml crème fraîche \n2 tsp grated nutmeg \n100g grated Parmesan \n1 tsp mustard powder \nTo Garnish \nParsley, chopped \nCook \n1. Heat the olive oil in a large, deep \ncasserole dish. Add leeks and garlic \nthen sauté for 6-8 minutes, until soft. \nAdd the caulifower forets and cook \nfor a further 2 minutes, stirring to \ncombine. Add in the Knorr Vegetable \nStock and cover with a lid, simmering \nfor 10-15 minutes until the caulifower \nis cooked through. \n2. Meanwhile, make the parmesan \ncrisps. Line a tray with a baking \nsheet, mix 100g of grated parmesan \nwith the mustard powder and \nspoon tablespoon-sized mounds on \nthe baking sheet. Leave an inch in \nbetween each mound. Bake in the \noven for 6 minutes, until the cheese \nis golden and has melted into fat \nrounds. Remove and allow to cool  \nand crisp up. \n3. When the caulifower is cooked, \nremove from the heat and allow \nto cool. Blend into a smooth,  \ncreamy soup with a hand blender. \nPlace back on the hob, over a  \nlow-medium heat and stir in the \ncrème fraîche, Parmesan, Gruyère  \nand grated nutmeg. \n4. Serve, topped with the Parmesan \ncrisps and some chopped herbs. \nThis recipe  \ncan also be \nused with a \nSTOCK \nPOT \nYour Guide To Soups\n \n \n \n \n \n \n \n \n \n \n \n \n  \n \n \nCaulifower \nCheese Soup \n10 \n11 \n\nIngredients \n1 Knorr Vegetable Stock Cube \n1 medium-sized sweet potato \n1 onion \n1 garlic clove \n1 tin of coconut milk \n1 small red chilli \n1 stick of lemongrass \n2 lime leaves \n1 tbsp olive oil \n450ml water \nGarnish \n1 lime \n1 red chilli, thinly sliced \nCook \n1. Heat the oil in a saucepan then sweat \nthe onion, garlic, lemongrass and chilli \nfor 5 minutes. \n2. Add the diced sweet potato and lime \nleaves then pour in the coconut milk, \nwater and Knorr Vegetable Stock \nCube then bring to the boil. \nRed Indonesian \nSweet Potatoes \nDid you know? Sweet \npotatoes are high in \nessential nutrients and \nhave 500x more vitamin \nE and 3x more vitamin C \nthan white potatoes. \n3. Simmer for 10 minutes or until the \npotatoes are soft. Remove the lime \nleaves and lemongrass then blend \nuntil smooth. \n4. Finish with a squeeze of lime and \ngarnish with thinly sliced red chilli. \nThis recipe  \ncan also be \nused with a \nSTOCK \nPOT \nYour Guide To Soups\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \nSweet Potato, \nCoconut &  \nLime Soup \nSpice things up with this comforting soup where every mouthful  \nis a perfect combo of sweetness, tang & kick. \nCooking time \n20 \nmins \n10 \nmins \n4 \npeople\nEASY \nDifculty \nPrep time \nServes \nKnorr ingredient \nFuture 50 Food \nKey \n12 \n13 \n\nTomato &  \nBasil Soup \nTry creating our delicious yet simple recipe for Basil  \nand Tomato Soup. \nIngredients \n1 Knorr Vegetable \nStock Pot \n400g tinned  \nplum tomatoes \n3 large tomatoes, chopped \n2 carrots, peeled and chopped \n2 celery sticks, chopped \n1 medium onion, chopped \nCook \n1. Heat the oil in a large pan, add the \ncarrots, celery, onion and garlic and \ncook on a low heat for 5 minutes or \nuntil the vegetables have started to \nsoften. \n2. Add the water, Knorr Vegetable Stock \nPot, tinned and fresh tomatoes and \nsimmer for 20 minutes. \n3. Add the basil, taste, and add pepper \nif needed. \n4. Blend until smooth, serve into bowls \nwith a spoonful of mascarpone and \nsome of the saved basil leaves. \nCooking time \n20 \nmins \n10 \nmins \n4 \npeople \nEASY \nDifculty \nPrep time \nServes \nKnorr ingredient \nKey \n2 cloves garlic, crushed \n400ml water \n2 tbsp olive oil \n20g basil \nFreshly ground pepper \n60g mascarpone (or a similar \nvegetarian alternative) \nThis recipe  \ncan also be \nused with a \nSTOCK\nCUBE \nYour Guide To Soups\n \n \n \n \n \n \n \n \n \n \n  \n \n14 \n15 \n\n'},
 {'file': 'docs\\documents_ca2\\research_paper.pdf',
  'type': 'pdf',

This pipeline processes a mixed dataset of images and PDF files to extract text for further NLP use. PDF files are handled using PyMuPDF, which directly extracts embedded digital text, resulting in highly accurate outputs. Image files are processed using Tesseract OCR, which converts visual content into machine-readable text. The quality of extracted text from images varies depending on the type of image: clear printed images (such as charts, diagrams, or scanned pages) produce better results, while handwritten images, blurred photos, or noisy scans often lead to incomplete or incorrect recognition due to OCR limitations. Therefore, differences in output quality are not caused by errors in the code, but by the nature and quality of the input data and the constraints of OCR technology when working with complex visual content.

Most of the images include scanned documents, photos (not scans), handwriting, artistic layouts, low contrast backgrounds. Without strong preprocessing, Tesseract struggles.

Next steps: Preprocessing, and improve config.

#### Creating a dataframe for the purpose of organising the above results

In [25]:
results_df = pd.DataFrame(results)

results_df

,file,type,text
0,docs\documents_ca2\aloevera_back.jpg,image,"See WET JUICE, weit; criabies US to capture tr..."
1,docs\documents_ca2\drawing_using_words.bmp,image,Yt She\nSe A ge ee 9 tok gi aa\nvie? i Been wh...
2,docs\documents_ca2\cartoon_drawing.pdf,pdf,4\nLesson\nFamous Artists Cartoon Course\nThe ...
3,docs\documents_ca2\know_receipe.pdf,pdf,Soups Recipe Book \n1 \n\nContents \nRecipes \...
4,docs\documents_ca2\research_paper.pdf,pdf,\nFig. 1. Classification algorithms \nThe ide...
5,docs\documents_ca2\scikit_learn.pdf,pdf,"05/05/2026, 22:21 1.1. Linear Models — scikit-..."
6,docs\documents_ca2\trinity_brochure.pdf,pdf,Undergraduate \nProspectus 2026\n\nContents \n...

The dataset contains a collection of mixed document types, including images and PDF files, all processed into a unified format for analysis. Each row represents a single document instance where the extracted text is obtained using OCR for images and a combination of direct text extraction and OCR fallback for PDFs. This allows both visual and textual content to be converted into machine-readable form. The resulting structure supports further NLP tasks such as text cleaning, feature extraction, and document understanding across heterogeneous sources within a single consistent dataset.

## Experiment 1 : Results:
represents the initial stage of the project, focusing on basic text extraction from images and PDF documents using OCR and document parsing techniques. This forms the foundation for later Vision preprocessing, NLP analysis, and multimodal integration. 

(Including the page numbers for all the pdf. so, each page in the pdf is a row.)

In [28]:
image_files = jpg_files + bmp_files

results = []

for file in image_files:
    img = cv2.imread(file)

    processed = preprocess_image(img)
    custom_config = r'--oem 1 --psm 6'  

    text = pytesseract.image_to_string(processed, config = custom_config)

    results.append({
        "file": file,
        "page": 0,
        "type": "image",
        "text": text
    })


#__________________________________

for file in pdf_files:
    doc = fitz.open(file)

    for page_num, page in enumerate(doc, start=1):
        text = page.get_text()

        # If text exists
        if text.strip():
            extracted_text = text

        # fallback OCR
        else:
            pix = page.get_pixmap(dpi=200)
            img = np.frombuffer(pix.samples, dtype=np.uint8)
            img = img.reshape(pix.height, pix.width, pix.n)

            custom_config = r'--oem 1 --psm 6'
            extracted_text = pytesseract.image_to_string(img, config=custom_config)

        results.append({
            "file": file,
            "page": page_num,
            "type": "pdf",
            "text": extracted_text
        })

In [29]:
results1_df = pd.DataFrame(results)

results1_df

,file,page,type,text
0,docs\documents_ca2\aloevera_back.jpg,0,image,"See WET JUICE, weit; criabies US to capture tr..."
1,docs\documents_ca2\drawing_using_words.bmp,0,image,Yt She\nSe A ge ee 9 tok gi aa\nvie? i Been wh...
2,docs\documents_ca2\cartoon_drawing.pdf,1,pdf,4\nLesson\nFamous Artists Cartoon Course\nThe ...
3,docs\documents_ca2\cartoon_drawing.pdf,2,pdf,Lesson\nFamous Artists Cartoon Course\nThe com...
4,docs\documents_ca2\cartoon_drawing.pdf,3,pdf,10\nAll cartoon characters are based on real p...
5,docs\documents_ca2\know_receipe.pdf,1,pdf,Soups Recipe Book \n1 \n
6,docs\documents_ca2\know_receipe.pdf,2,pdf,Contents \nRecipes \nQuick & Easy Soups – 20 m...
7,docs\documents_ca2\know_receipe.pdf,3,pdf,Jackfruit \nWhy not try going \nmeat free one ...
8,docs\documents_ca2\know_receipe.pdf,4,pdf,White potatoes \nFOR \nSweet potatoes \nKidney...
9,docs\documents_ca2\know_receipe.pdf,5,pdf,Creamy Pea Soup \nPerfect mid-week lunch when ...
10,docs\documents_ca2\know_receipe.pdf,6,pdf,This rich and creamy caulifower soup with an i...
11,docs\documents_ca2\know_receipe.pdf,7,pdf,Ingredients \n1 Knorr Vegetable Stock Cube \n1...
12,docs\documents_ca2\know_receipe.pdf,8,pdf,Tomato & \nBasil Soup \nTry creating our deli...
13,docs\documents_ca2\research_paper.pdf,1,pdf,\nFig. 1. Classification algorithms \nThe ide...
14,docs\documents_ca2\research_paper.pdf,2,pdf,\nFig. 2. RBF Network \nThe neuron’s response...
15,docs\documents_ca2\research_paper.pdf,3,pdf,NB classifier is widely employed for two class...
16,docs\documents_ca2\scikit_learn.pdf,1,pdf,"05/05/2026, 22:21 1.1. Linear Models — scikit-..."
17,docs\documents_ca2\scikit_learn.pdf,2,pdf,"05/05/2026, 22:21 1.1. Linear Models — scikit-..."
18,docs\documents_ca2\scikit_learn.pdf,3,pdf,"05/05/2026, 22:21 1.1. Linear Models — scikit-..."
19,docs\documents_ca2\trinity_brochure.pdf,1,pdf,Undergraduate \nProspectus 2026\n
20,docs\documents_ca2\trinity_brochure.pdf,2,pdf,Contents \n2 \nProvost’s Welcome\n4 \nWhy Choo...
21,docs\documents_ca2\trinity_brochure.pdf,3,pdf,"Science, Technology, \nEngineering and Mathem..."
22,docs\documents_ca2\trinity_brochure.pdf,4,pdf,Welcome to our \n2026 prospectus\nI have the g...
23,docs\documents_ca2\trinity_brochure.pdf,5,pdf,\n9\nwww.tcd.ie/study\n9\nwww.tcd.ie/study\nH...
24,docs\documents_ca2\trinity_brochure.pdf,6,pdf,Student Life at Trinity \nYour First Months at...
25,docs\documents_ca2\trinity_brochure.pdf,7,pdf,"The Pav\nThe Pavilion Bar, affectionately know..."
26,docs\documents_ca2\trinity_brochure.pdf,8,pdf,"Sports Centre\nThe Sports Centre, located at t..."
27,docs\documents_ca2\trinity_brochure.pdf,9,pdf,German\nB.A. Honours Bachelor Degree (NFQ Leve...
28,docs\documents_ca2\trinity_brochure.pdf,10,pdf,History\nB.A. Honours Bachelor Degree (NFQ Lev...
29,docs\documents_ca2\trinity_brochure.pdf,11,pdf,\nTrinity Campus\nMap\n21\nCOLLEGE GREEN\n19\...
30,docs\documents_ca2\trinity_brochure.pdf,12,pdf,Trinity Open Day 2025\nSaturday 29th November ...

The current system is in the early exploratory stage, focusing on basic OCR-based extraction from images and PDFs. This forms the foundation for future Vision preprocessing, NLP analysis, and multimodal integration.

In [31]:
# step 6: NLP

texts = [item["text"] for item in results]

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X = tfidf.fit_transform(texts)

ModuleNotFoundError: No module named 'sklearn'

# Vision

## Sub Heading 1

In [ ]:
# code here...

# Multi-modal

## Sub Heading 1

In [ ]:
# code here

# Final Output

In [ ]:
# code